/* Generated by Yosys 0.65 (git sha1 aec814bdf3071f7e0fd0fbe43f7f711e99d01e24, clang++ 21.0.0 -fPIC -O3) */

/* top =  1  */
/* src = "/Users/sandeep/risc-v/single_cycle/instruction_memory.sv:4.1-12.10" */
module instructionmemory(A, RD);
  /* src = "/Users/sandeep/risc-v/single_cycle/instruction_memory.sv:6.24-6.25" */
  input [31:0] A;
  /* src = "/Users/sandeep/risc-v/single_cycle/instruction_memory.sv:7.25-7.27" */
  output [31:0] RD;
  assign RD = 32'hxxxxxxxx;
endmodule